- name: Install yay
  block:
    - name: Install yay via pacman, assuming there is a repo that provides it
      community.general.pacman:
        name: yay
        state: present
      failed_when: "'error' in command_result.stderr"
  rescue:
    - name: Clone yay repository
      ansible.builtin.git:
        repo: https://aur.archlinux.org/yay-bin.git
        dest: "{{ yay_dir }}"
        update: true

    - name: Make and install yay package
      ansible.builtin.command:
        chdir: "{{ yay_dir }}"
        cmd: "makepkg -sfi --noconfirm"
        creates: /usr/bin/yay
