---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - git
      - zsh
    state: present

- name: Clone dotfile repo to $HOME/.dots
  ansible.builtin.git:
    repo: https://github.com/rowlul/dots.git
    dest: "$HOME/.dots"
    bare: true
  become: false

- name: Check out dotfile repo to $HOME
  ansible.builtin.command: # built-in module can't replicate this behavior
    cmd: '/usr/bin/git --git-dir="$HOME/.dots/" --work-tree="$HOME/" checkout' # noqa: command-instead-of-module
    creates: "$HOME/.zshenv"
  failed_when: false
  become: false

- name: Turn off status.showUntrackedFiles
  community.general.git_config:
    name: status.showUntrackedFiles
    value: "no"
    scope: local
    repo: "$HOME/.dots"
  become: false

- name: Set origin url to ssh
  community.general.git_config:
    name: remote.origin.url
    value: git@github.com:rowlul/dots.git
    scope: local
    repo: "$HOME/.dots"
  become: false

- name: Get running user
  ansible.builtin.set_fact:
    __env_username: "{{ lookup('env', 'USER') }}"
  become: false

- name: Set running user's shell to /bin/zsh
  ansible.builtin.user:
    name: "{{ __env_username }}"
    shell: "/bin/zsh"
