---
- name: Install rustup
  community.general.pacman:
    name: rustup
    state: present

- name: Set default toolchain version
  ansible.builtin.shell: rustup default stable-x86_64-unknown-linux-gnu
  become_user: "{{ user }}"

- name: Install cargo tools
  community.general.pacman:
    name:
     - cargo-binstall
     - cargo-sort
     - cargo-watch
     - cargo-bloat
     - cargo-update
     - cargo-release
    state: present
