---
asusd_charge_limit: 60
asusd_fan_curve:
  - mode: Balanced
    fan: cpu
    data: 20c:0%,49c:0%,58c:1%,62c:29%,65c:50%,72c:100%,80c:100%,100c:100%
  - mode: Balanced
    fan: gpu
    data: 20c:0%,52c:0%,56c:20%,60c:40%,68c:51%,70c:100%,80c:100%,100c:100%
  - mode: Performance
    fan: cpu
    data: 20c:0%,49c:0%,58c:1%,62c:29%,65c:50%,72c:100%,80c:100%,100c:100%
  - mode: Performance
    fan: gpu
    data: 20c:0%,52c:0%,56c:20%,60c:40%,68c:51%,70c:100%,80c:100%,100c:100%
asusd_anime_enabled: false
asusd_boot_sound: false
asusd_screen_overdrive: false
