---
- name: Disable watchdog kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: absent
  loop: "{{ watchdog_kernel_modules }}"

- name: Create a denylist of watchdog kernel modules
  ansible.builtin.copy:
    dest: /etc/modprobe.d/watchdog.conf
    mode: '0644'
    content: |
      {% for module in watchdog_kernel_modules %}
      {{ module }}
      {% endfor %}
