---
- name: Provision dev machine infrastructure
  hosts: all
  become: true

  pre_tasks:
    - name: Initialize playbook
      any_errors_fatal: true
      block:
        - name: Ensure running distribution is Arch Linux
          ansible.builtin.assert:
            that: ansible_distribution == "Archlinux"

        - name: Get user id
          ansible.builtin.getent:
            database: passwd
            key: "{{ user }}"
          register: getent_user

        - name: Persist user id
          ansible.builtin.set_fact:
            uid: "{{ lookup('ansible.builtin.dict', getent_user).0.1 }}"

  post_tasks:
    - name: Install packages
      community.general.pacman:
        name: "{{ packages }}"
        state: present

    - name: Install flatpaks
      community.general.flatpak:
        name: "{{ packages }}"
        state: present

  roles:
    # package acquisition
    - role: pacman
      tags: pacman

    - role: multilib
      tags: multilib
      when: multilib

    - role: chaotic_aur
      tags: chaotic_aur

    # server
    - role: ssh
      tags: ssh
      when: ssh

    - role: samba
      tags: samba
      when: samba

    # system optimization
    - role: ananicy
      tags: ananicy

    - role: btrfsmaintenance
      tags: btrfsmaintenance
      when: btrfs

    - role: systemd_journald
      tags: systemd_journald

    - role: watchdog
      tags: watchdog

    - role: zram
      tags: zram
      when: zram

    - role: ioschedulers
      tags: ioschedulers

    - role: informant
      tags: informant

    # virtualization
    - role: docker
      tags: docker
      when: docker

    - role: libvirt
      tags: libvirt
      when: libvirt

    # graphics
    - role: amdgpu
      tags: amdgpu
      when: amdgpu

    - role: gnome
      tags: gnome
      when: gnome

    # devices
    - role: opentabletdriver
      tags: opentabletdriver
      when: opentabletdriver
