---
- hosts: all
  name: Provision dev machine infrastructure
  become: true
  vars:
    temp_dir: /tmp/ansible
    yay_dir: "{{ yay_dir }}/yay"

  pre_tasks:
    - name: Get user id
      ansible.builtin.getent:
        database: passwd
        key: "{{ user }}"
      register: getent_user
      any_errors_fatal: true

    - name: Persist user id
      ansible.builtin.set_fact:
        uid: "{{ lookup('ansible.builtin.dict', getent_user).0.1 }}"

  post_tasks:
    - name: Clean up temporary files
      ansible.builtin.file:
        path: "{{ temp_dir }}"
        state: absent

  roles:
    # package acquisition
    - role: pacman
      tags: pacman

    - role: chaotic_aur
      tags: chaotic_aur

    # server
    - role: ssh
      tags: ssh
      when: ssh

    - role: samba
      tags: samba
      when: samba

    # system optimization
    - role: ananicy
      tags: ananicy

    - role: btrfsmaintenance
      tags: btrfsmaintenance
      when: btrfs

    - role: systemd_journald
      tags: systemd_journald

    - role: watchdog
      tags: watchdog

    - role: zram_generator
      tags: zram_generator
      when: zram

    - role: zram_hibernate
      tags: zram_hibernate
      when: zram

    - role: ioschedulers
      tags: ioschedulers

    - role: informant
      tags: informant

    # virtualization
    - role: docker
      tags: docker
      when: docker

    - role: libvirt
      tags: libvirt
      when: libvirt

    # programming languages
    - role: dotnet
      tags: dotnet
      when: dotnet

    - role: java
      tags: java
      when: java

    - role: python
      tags: python
      when: python

    - role: golang
      tags: golang
      when: golang

    - role: nodejs
      tags: nodejs
      when: nodejs

    - role: rust
      tags: rust
      when: rust

    # graphics
    - role: amdgpu
      tags: amdgpu
      when: gnome

    - role: fonts
      tags: fonts
      when: gnome

    - role: gnome
      tags: gnome
      when: gnome

    - role: apps
      tags: apps
      when: apps

    # gaming
    - role: wine
      tags: wine
      when: wine

    - role: wine_gaming
      tags: wine_gaming
      when: wine_gaming

    - role: lutris
      tags: lutris
      when: lutris

    - role: steam
      tags: steam
      when: steam

    # devices
    - role: opentabletdriver
      tags: opentabletdriver
      when: opentabletdriver

    - role: openrazer
      tags: openrazer
      when: openrazer

    # extras
    - role: rocm
      tags: rocm
      when: rocm

    - role: msfonts
      tags: msfonts
      when: gnome and msfonts
