---
- hosts: all
  name: Provision dev machine infrastructure
  become: true
  vars:
    temp_dir: /tmp/ansible
    yay_dir: "{{ yay_dir }}/yay"

  pre_tasks:
    - name: Get user id
      ansible.builtin.getent:
        database: passwd
        key: "{{ user }}"
      register: getent_user
      any_errors_fatal: true

    - name: Persist user id
      ansible.builtin.set_fact:
        uid: "{{ lookup('ansible.builtin.dict', getent_user).0.1 }}"

  post_tasks:
    - name: Clean up temporary files
      ansible.builtin.file:
        path: "{{ temp_dir }}"
        state: absent

  roles:
    # package acquisition
    - role: pacman
      tags: pacman

    - role: multilib
      tags: multilib

    - role: chaotic_aur
      tags: chaotic_aur

    - role: yay
      tags: yay

    # server
    - role: ssh
      tags: ssh

    - role: samba
      tags: samba

    # system optimization
    - role: ananicy
      tags: ananicy

    - role: btrfsmaintenance
      tags: btrfsmaintenance

    - role: systemd_journald
      tags: systemd_journald

    - role: watchdog
      tags: watchdog

    - role: zram_generator
      tags: zram_generator

    - role: zram_hibernate
      tags: zram_hibernate

    - role: ioschedulers
      tags: ioschedulers

    - role: informant
      tags: informant

    # virtualization
    - role: docker
      tags: docker

    - role: libvirt
      tags: libvirt

    # programming languages
    - role: dotnet
      tags: dotnet

    - role: java
      tags: java

    - role: python
      tags: python

    - role: golang
      tags: golang

    - role: nodejs
      tags: nodejs

    - role: rust
      tags: rust

    # graphics
    - role: amdgpu
      tags: amdgpu

    - role: fonts
      tags: fonts

    - role: gnome
      tags: gnome

    - role: apps
      tags: apps

    # gaming
    - role: wine
      tags: wine

    - role: wine_gaming
      tags: wine_gaming

    - role: lutris
      tags: lutris

    - role: steam
      tags: steam

    # devices
    - role: opentabletdriver
      tags: opentabletdriver

    - role: openrazer
      tags: openrazer

    # extras
    - role: rocm
      tags: rocm

    - role: msfonts
      tags: msfonts
