---
- name: Provision dev machine infrastructure
  hosts: all
  become: true

  pre_tasks:
    - name: Initialize playbook
      any_errors_fatal: true
      block:
        - name: Ensure running distribution is Arch Linux
          ansible.builtin.assert:
            that: ansible_distribution == "Archlinux"

        - name: Get user {{ user }}
          ansible.builtin.getent:
            database: passwd
            key: "{{ user }}"

  tasks:
    - name: Include role {{ item }}
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ run }}"

  post_tasks:
    - name: Install packages
      community.general.pacman:
        name: "{{ packages }}"
        state: present

    - name: Install flatpaks
      community.general.flatpak:
        name: "{{ packages }}"
        state: present
