---
- name: Provision dev machine infrastructure
  hosts: all
  become: true

  tasks:
    - name: Ensure running distribution is Arch Linux
      ansible.builtin.assert:
        that: ansible_distribution == "Archlinux"
      any_errors_fatal: true

    - name: Get user {{ user }}
      ansible.builtin.getent:
        database: passwd
        key: "{{ user }}"
      any_errors_fatal: true

    - name: Include run roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ run }}"

    - name: Include post run roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ post_run }}"
      when: post_run is defined and post_run | length > 0

    - name: Install packages
      community.general.pacman:
        name: "{{ packages }}"
        state: present
      when: packages is defined and packages | length > 0

    - name: Post install packages
      community.general.pacman:
        name: "{{ packages }}"
        state: present
      when: post_packages is defined and packages | length > 0

    - name: Install flatpaks
      community.general.flatpak:
        name: "{{ flatpaks }}"
        state: present
      when: |
        flatpak is defined and flatpak is true and
        flatpaks is defined and flatpaks | length > 0
