---
- name: Install graphics stack
  community.general.pacman:
    name:
      - wayland
      - wayland-protocols
      - wayland-utils
      - wlroots
      - wl-clipboard
      - ydotool
      - xorg-xwayland
    state: present

- name: Install audio stack
  community.general.pacman:
    name:
      - pipewire
      - pipewire-pulse
      - pipewire-jack
      - wireplumber
    state: present
    extra_args: '--noconfirm --ask=4'

- name: Install GUI frameworks
  community.general.pacman:
    name:
      - libadwaita
      - gtk3
      - gtk4
      - qt5-base
      - qt6-base
      - qt5-wayland
      - qt6-wayland
    state: present

- name: Install XDG packages
  community.general.pacman:
    name:
      - xdg-utils
      - xdg-user-dirs
      - xdg-user-dirs-gtk
      - libcanberra
      - libnotify
    state: present

- name: Check if user-dirs.dirs exists
  ansible.builtin.stat:
    path: "$HOME/.config/user-dirs.dirs"
  register: user_dirs_fs
  become: false

- name: Read user-dirs.dirs
  ansible.builtin.command:
    cmd: cat "$HOME/.config/user-dirs.dirs"
  register: user_dirs_file
  become: false
  when: user_dirs_fs.stat.exists

- name: Parse and create XDG directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ user_dirs_file.stdout_lines | select('match', '^XDG_.*_DIR') | map('regex_replace', '^XDG_.*_DIR=\"(.*?)\"$', '\\1') | list }}"
  become: false
  when: user_dirs_fs.stat.exists

- name: Update xdg-user-dirs
  ansible.builtin.command:
    cmd: xdg-user-dirs-update
  become: false

- name: Create ~/.local/share/applications
  ansible.builtin.file:
    path: "$HOME/.local/share/applications"
    state: directory
    mode: '0755'
  become: false

- name: Hide certain .desktop files
  ansible.builtin.copy:
    dest: "$HOME/.local/share/applications/{{ item }}.desktop"
    content: |
      [Desktop Entry]
      NoDisplay=true
    mode: '0644'
  loop: "{{ desktop_files_to_hide }}"
  become: false
