---
- name: Include multilib repository in pacman.conf
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    prepend_newline: true
    append_newline: true
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: Refresh pacman cache
  community.general.pacman:
    update_cache: true

- name: Set multilib fact
  ansible.builtin.set_fact:
    multilib: true
