---
- name: Install zram-generator package
  community.general.pacman:
    name: zram-generator
    state: present

- name: Create zram-generator.conf
  ansible.builtin.template:
    src: zram-generator.j2
    dest: /etc/systemd/zram-generator.conf
    mode: '0644'
  notify:
    - Reload systemd daemon
    - Start zram

- name: Use optimized sysctl parameters for zram
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-vm-zram-parameters.conf
  loop: "{{ zram_sysctl_params | dict2items }}"
