---
- name: Create journald.conf
  ansible.builtin.template:
    src: journald.j2
    dest: /etc/systemd/journald.conf
    mode: '0644'

- name: Restart systemd-journald service
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
