---
- name: Install samba
  community.general.pacman:
    name: samba
    state: present

- name: Create smb.conf
  ansible.builtin.template:
    src: smb.j2
    dest: /etc/samba/smb.conf
    mode: '0644'
