---
- name: Install informant
  community.general.pacman:
    name: informant
    state: present
    executable: yay
    extra_args: "--builddir {{ yay_dir }}"

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: informant
    append: yes
