---
- name: Install informant
  community.general.pacman:
    name: informant
    state: present

- name: Create informant group
  ansible.builtin.group:
    name: informant
    system: true

- name: Add user to informant group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: informant
    append: true
