---
- name: Install steam package
  community.general.pacman:
    name: steam
    state: present

- name: Install protonup-qt
  community.general.pacman:
    name: protonup-qt
    state: present
    executable: yay
    extra_args: "--builddir {{ yay_dir }}"
