---
- name: Install steam package
  community.general.pacman:
    name: steam
    state: present

- name: Install protontricks package
  community.general.pacman:
    name: protontricks-git
    state: present
    executable: yay
    extra_args: "--builddir {{ yay_dir }}"
