---
- name: Create systemd-journal group
  ansible.builtin.group:
    name: systemd-journal
    system: true

- name: Create journald.conf
  ansible.builtin.copy:
    src: journald.conf
    dest: /etc/systemd/journald.conf
    mode: '0644'

- name: Restart systemd-journald service
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
