---
- name: Install python
  community.general.pacman:
    name: python
    state: present

- name: Install pip
  community.general.pacman:
    name: go
    state: present

- name: Install poetry
  community.general.pacman:
    name: python-poetry
    state: present

- name: Install rye
  community.general.pacman:
    name: rye
    state: present

- name: Install black
  community.general.pacman:
    name: python-black
    state: present

- name: Install flake8
  community.general.pacman:
    name: flake8
    state: present

- name: Install mypy
  community.general.pacman:
    name: mypy
    state: present
