---
- name: Create kvm.conf
  ansible.builtin.copy:
    src: kvm.conf
    dest: /etc/modprobe.d/kvm.conf
    mode: '0644'

- name: Install libvirt and some optional packages
  community.general.pacman:
    name:
      - libvirt
      - dmidecode
      - dnsmasq
      - iptables-nft
    state: present
    extra_args: '--noconfirm --ask=4'
    # using undocumented args to resolve dep conflict (iptables -> iptables-nft)
    # https://gitlab.archlinux.org/pacman/pacman/-/issues/60#note_131424

- name: Install qemu-desktop package
  community.general.pacman:
    name: qemu-desktop
    state: present

- name: Get running user
  ansible.builtin.set_fact:
    __env_username: "{{ lookup('env', 'USER') }}"
  become: false

- name: Create libvirtd.conf
  ansible.builtin.template:
    src: libvirtd.j2
    dest: /etc/libvirt/libvirtd.conf
    mode: '0644'

- name: Create qemu.conf
  ansible.builtin.template:
    src: qemu.j2
    dest: /etc/libvirt/qemu.conf
    mode: '0644'

- name: Create libvirt group
  ansible.builtin.group:
    name: libvirt
    system: true

- name: Add user to libvirt group
  ansible.builtin.user:
    name: "{{ __env_username }}"
    groups: libvirt
    append: true
