---
- name: Install openssh package
  community.general.pacman:
    name: openssh
    state: present

- name: Generate random port
  ansible.builtin.set_fact:
    port: "{{ 65535 | random(start=1024) }}"
  run_once: true

- name: Create sshd_config
  ansible.builtin.copy:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0644

- name: Enable and start sshd service
  ansible.builtin.systemd:
    name: sshd
    state: started
    enabled: true
