---
- name: Install ananicy-cpp
  community.general.pacman:
    name: ananicy-cpp
    state: present

- name: Install cachyos-ananicy-rules-git
  community.general.pacman:
    name: cachyos-ananicy-rules-git
    state: present

- name: Enable and start ananicy-cpp.service
  ansible.builtin.systemd:
    name: ananicy-cpp
    enabled: true
    state: started
