---
- name: Install openrazer packages
  community.general.pacman:
    name:
      - openrazer-daemon
      - openrazer-driver-dkms
      - python-openrazer
    state: present

- name: Install polychromatic package
  community.general.pacman:
    name: polychromatic
    state: present
    executable: yay
    extra_args: "--builddir {{ yay_dir }}"
