---
- name: Add input sources
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'us'), ('xkb', 'lv+apostrophe'), ('xkb', 'ru'), ('xkb', 'de')]"
    state: present

- name: 24h clock
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "24h"
    state: present

- name: Prefer dark color scheme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "prefer-dark"
    state: present

- name: Set font to Ubuntu
  community.general.dconf:
    key: "/org/gnome/desktop/interface/{{ item }}"
    value: "Ubuntu 11"
    state: present
  loop:
    - document-font-name
    - font-name

- name: Set gtk 3 theme to adw-gtk3-dark
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "adw-gtk3-dark"
    state: present

- name: Disable autorun
  community.general.dconf:
    key: "/org/gnome/desktop/media-handling/autorun-never"
    value: true
    state: present

- name: Set acceleration profile to flat
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/mouse/accel-profile"
    value: "flat"
    state: present

- name: Disable event sounds
  community.general.dconf:
    key: "/org/gnome/desktop/sound/event-sounds"
    value: false
    state: present

- name: Disable autorun
  community.general.dconf:
    key: "/org/gnome/desktop/media-handling/autorun-never"
    value: true
    state: present

- name: Set button layout
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "appmenu:minimize,maximize,close"
    state: present

- name: Set title bar font to Ubuntu
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/titlebar-font"
    value: "Ubuntu 11"
    state: present

- name: Center new windows
  community.general.dconf:
    key: "/org/gnome/mutter/center-new-windows"
    value: true
    state: present

- name: Make alive timeout long
  community.general.dconf:
    key: "/org/gnome/mutter/check-alive-timeout"
    value: 60000
    state: present

- name: Disable dynamic workspaces
  community.general.dconf:
    key: "/org/gnome/mutter/dynamic-workspaces"
    value: false
    state: present

- name: Enable edge tiling
  community.general.dconf:
    key: "/org/gnome/mutter/edge-tiling"
    value: true
    state: present

- name: Set default zoom level
  community.general.dconf:
    key: "/org/gnome/nautilus/icon-view/default-zoom-level"
    value: "medium"
    state: present

- name: Set default zoom level
  community.general.dconf:
    key: "/org/gnome/nautilus/list-view/default-zoom-level"
    value: "small"
    state: present

- name: Set default folder viewer
  community.general.dconf:
    key: "/org/gnome/nautilus/preferences/default-folder-viewer"
    value: "list-view"
    state: present

- name: Set search viewer
  community.general.dconf:
    key: "/org/gnome/nautilus/preferences/search-view"
    value: "list-view"
    state: present

- name: Limit switcher to current workspace
  community.general.dconf:
    key: "/org/gnome/shell/app-switcher/current-workspace-only"
    value: true
    state: present

- name: Enable development tools
  community.general.dconf:
    key: "/org/gnome/shell/development-tools"
    value: true
    state: present

- name: Enable user extensions
  community.general.dconf:
    key: "/org/gnome/shell/disable-user-extensions"
    value: false
    state: present
