---
- name: Create 60-ioschedulers.rules
  ansible.builtin.copy:
    src: 60-ioschedulers.rules
    dest: /etc/udev/rules.d/60-ioschedulers.rules
    mode: '0644'

- name: Reload udev rules
  ansible.builtin.shell:
    cmd: udevadm control --reload-rules && udevadm trigger
