---
- name: Enable pacman options
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?\s*{{ item }}\s'
    line: "{{ item }}"
  loop:
    - Color
    - VerbosePkgLists
    - ParallelDownloads = 5

- name: Enable 'ILoveCandy' pacman option
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    insertafter: "ParallelDownloads = 5"
    line: "ILoveCandy"

- ansible.builtin.import_tasks:
    file: multilib.yml
  when: pacman_multilib

- ansible.builtin.import_tasks:
    file: chaotic_aur.yml
  when: pacman_chaotic_aur

- name: Refresh pacman cache
  community.general.pacman:
    update_cache: true

- ansible.builtin.import_tasks:
    file: reflector.yml
  when: pacman_reflector

- ansible.builtin.import_tasks:
    file: cache_cleanup.yml
  when: pacman_cache_cleanup
