---
- name: Enable some pacman options
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?\s*{{ item.key }}\s'
    line: "{{ item }}"
  loop:
    - Color
    - CheckSpace
    - VerbosePkgLists
    - ParallelDownloads = 5

- name: Enable 'ILoveCandy' pacman option
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    insertafter: "ParallelDownloads = 5"
    line: "ILoveCandy"
