---
- name: Start zram
  ansible.builtin.systemd:
    state: started
    name: "systemd-zram-setup@zram{{ index }}"
    enabled: true
  loop: "{{ zram_devices }}"
  loop_control:
    index_var: index
