---
- name: Install CLI apps
  community.general.pacman:
    name:
      - btop
      - htop
      - aria2
      - yt-dlp
      - just
      - grex
      - ripgrep
      - bat
      - neovim
      - lazydocker
      - broot
      - neofetch
      - pfetch
      - yank
      - bitwarden-cli
      - speedtest-cli
      - tldr
      - navi
      - man
      - jd
      - yq
      - xq
      - figlet
      - trash-cli
      - gdu
      - rsync
      - rclone
      - lsd
      - autojump
      - fzf
      - lazygit
      - github-cli
      - gitlab-cli
      - cmatrix
      - pandoc-bin
      - shellcheck-bin
      - shfmt
      - unrar
      - unzip
      - p7zip
      - ffmpeg
    state: present
    executable: yay
    extra_args: "--builddir {{ yay_dir }}"

- name: Install GUI apps (pacman)
  community.general.pacman:
    name:
      - ungoogled-chromium
      - kitty
      - rhythmbox
      - qbittorrent
      - celluloid
      - gparted
      - jetbrains-toolbox
      - prismlauncher
      - protonvpn-cli
      - protonvpn-gui
      - rustdesk-bin
      - virt-manager
      - ventoy-bin
      - woeusb-ng
    state: present
    executable: yay
    extra_args: "--builddir {{ yay_dir }}"

- name: Install GUI apps (flatpak)
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - com.github.johnfactotum.Foliate
      - com.github.micahflee.torbrowser-launcher
      - com.github.tchx84.Flatseal
      - com.spotify.Client
      - md.obsidian.Obsidian
      - org.onlyoffice.desktopeditors
      - rest.insomnia.Insomnia
    state: present
    method: user
  become_user: "{{ user }}"
