---
- name: Install wine and optional packages
  community.general.pacman:
    name:
      - wine
      - giflib
      - lib32-giflib
      - libldap
      - lib32-libldap
      - gnutls
      - lib32-gnutls
      - v4l-utils
      - lib32-v4l-utils
      - libpulse
      - lib32-libpulse
      - alsa-plugins
      - lib32-alsa-plugins
      - lib32-alsa-lib
      - libxcomposite
      - lib32-libxcomposite
      - libxinerama
      - lib32-libxinerama
      - gst-plugins-base-libs
      - lib32-gst-plugins-base-libs
      - sdl2
      - lib32-sdl2
      - libpng
      - lib32-libpng
      - mpg123
      - lib32-mpg123
      - openal
      - libgpg-error
      - lib32-libgpg-error
      - libjpeg-turbo
      - lib32-libjpeg-turbo
      - sqlite
      - lib32-sqlite
      - lib32-libgcrypt
      - libgcrypt
      - ncurses
      - lib32-ncurses
      - ocl-icd
      - lib32-ocl-icd
      - libxslt
      - lib32-libxslt
      - gst-plugins-base-libs
      - lib32-gst-plugins-base-libs
    state: present

- name: Install winetricks package
  community.general.pacman:
    name: winetricks
    state: present

- name: Install protonup-qt
  community.general.pacman:
    name: protonup-qt
    state: present
    executable: yay
    extra_args: "--builddir {{ yay_dir }}"

- name: Install mangohud
  community.general.pacman:
    name:
      - mangohud
      - lib32-mangohud
    state: present
    executable: yay
    extra_args: "--builddir {{ yay_dir }}"

- name: Install goverlay
  community.general.pacman:
    name: gamescope
    state: present
    executable: yay
    extra_args: "--builddir {{ yay_dir }}"

- name: Install gamemode
  community.general.pacman:
    name:
      - gamemode
      - lib32-gamemode
    state: present
    executable: yay
    extra_args: "--builddir {{ yay_dir }}"
