---
- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Enable and start firewalld service
  ansible.builtin.systemd:
    name: firewalld.service
    state: started
    enabled: true
