---
- name: Install docker
  community.general.pacman:
    name: docker
    state: present

- name: Install docker-compose
  community.general.pacman:
    name: docker-compose
    state: present

- name: Create docker group
  ansible.builtin.group:
    name: docker
    system: true

- name: Get running user
  ansible.builtin.set_fact:
    __env_username: "{{ lookup('env', 'USER') }}"
  become: false

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ __env_username }}"
    groups: docker
    append: true
