---
- name: Install docker
  community.general.pacman:
    name: docker
    state: present

- name: Install docker-compose
  community.general.pacman:
    name: docker-compose
    state: present

- name: Create docker group
  ansible.builtin.group:
    name: docker
    system: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
