---
- name: Install zram-generator package
  community.general.pacman:
    name: zram-generator
    state: present

- name: Create zram-generator.conf
  ansible.builtin.copy:
    src: zram-generator.conf
    dest: /etc/systemd/zram-generator.conf
    mode: preserve

- name: Reload systemd targets
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start zram
  ansible.builtin.systemd:
    state: started
    name: systemd-zram-setup@zram0
    enabled: true
