---
- name: Disable all watchdog modules
  community.general.modprobe:
    name:
      - sp5100_tco
      - iTCO_wdt
      - iTCO_vendor_support
      - wdat_wdt
    state: absent
    persistent: present
