---
- name: Install btrfsmaintenance
  community.general.pacman:
    name: btrfsmaintenance
    state: present

- name: Enable btrfsmaintenance timers
  ansible.builtin.systemd:
    name: "{{ item }}.timer"
    state: started
    enabled: true
  loop:
    - btrfs-balance
    - btrfs-scrub
