---
- name: Install openssh package
  community.general.pacman:
    name: openssh
    state: present

- name: Generate random port
  ansible.builtin.set_fact:
    ssh_port: "{{ 65535 | random(start=1024) }}"
  when: ssh_port is undefined

- name: Show ssh port
  ansible.builtin.debug:
    var: ssh_port

- name: Create sshd_config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: '0644'
