---
- name: Install packages
  community.general.pacman:
    name:
      - mesa
      - xf86-video-amdgpu
      - vulkan-radeon
      - libva-mesa-driver
      - mesa-vdpau
      - rocm-smi-lib
    state: present

- name: Install 32-bit packages
  community.general.pacman:
    name:
      - lib32-mesa
      - lib32-vulkan-radeon
      - lib32-libva-mesa-driver
      - lib32-mesa-vdpau
    state: present
  when: pacman_multilib | default('false')
