---
- name: Install mesa packages
  community.general.pacman:
    name:
      - mesa
      - xf86-video-amdgpu
      - vulkan-radeon
      - libva-mesa-driver
      - mesa-vdpau
    state: present

- name: Install 32-bit mesa packages
  community.general.pacman:
    name:
      - lib32-mesa
      - lib32-vulkan-radeon
      - lib32-libva-mesa-driver
      - lib32-mesa-vdpau
    state: present
  when: multilib

- name: Check whether /etc/mkinitcpio.conf contains "amdgpu"
  ansible.builtin.command: grep -q 'MODULES=.*amdgpu' /path/to/mkinitcpio.conf
  ignore_errors: true
  register: amdgpu_check

- name: Add "amdgpu" to modules in /etc/mkinitcpio.conf
  ansible.builtin.lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^MODULES=\((.*)\)'
    line: 'MODULES=(\1 amdgpu)'
    backrefs: true
  when: amdgpu_check.rc != 0
